import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const STATUSES = ["OPEN", "OPEN", "OPEN", "RESOLVED", "CLOSED"] as const;
const CATEGORIES = [
  "GENERAL_QUESTION",
  "TECHNICAL_QUESTION",
  "TECHNICAL_QUESTION",
  "REFUND_REQUEST",
] as const;

const tickets: Array<{
  subject: string;
  body: string;
  fromName: string;
  fromEmail: string;
  status: (typeof STATUSES)[number];
  category: (typeof CATEGORIES)[number] | null;
  createdAt: Date;
}> = [
  // REFUND_REQUEST
  {
    subject: "Request refund for duplicate charge",
    body: "Hi, I was charged twice for my subscription on March 3rd. Both charges of $49.99 appear on my bank statement. Please refund the duplicate.",
    fromName: "Sarah Mitchell",
    fromEmail: "sarah.mitchell@gmail.com",
    status: "OPEN",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(1),
  },
  {
    subject: "Refund for cancelled order #8821",
    body: "I cancelled my order within the 30-minute window but still got charged. Order #8821, placed on April 28. Please process the refund.",
    fromName: "James Okafor",
    fromEmail: "j.okafor@hotmail.com",
    status: "OPEN",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(2),
  },
  {
    subject: "Wrong item delivered — want full refund",
    body: "I ordered the blue backpack (SKU BG-4421) but received a red one. I don't want a replacement, just a full refund. I can ship it back.",
    fromName: "Priya Sharma",
    fromEmail: "priya.sharma@outlook.com",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(5),
  },
  {
    subject: "Subscription charged after cancellation",
    body: "I cancelled my plan on April 1st but was charged again on May 1st. This is unacceptable. Please refund $29/month immediately.",
    fromName: "Tom Bradshaw",
    fromEmail: "tombradshaw@yahoo.com",
    status: "CLOSED",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(20),
  },
  {
    subject: "Partial refund for damaged goods",
    body: "Two of the four items in my order arrived damaged. I'd like a partial refund for those two items. Order #10045.",
    fromName: "Chloe Dupont",
    fromEmail: "chloe.dupont@sfr.fr",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(8),
  },
  {
    subject: "Charged for plan I never signed up for",
    body: "I signed up for the free tier but somehow got charged $99 for the Enterprise plan. I've never agreed to this. Please refund.",
    fromName: "Kevin Nguyen",
    fromEmail: "kevin.nguyen@proton.me",
    status: "OPEN",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(1),
  },
  {
    subject: "Event ticket refund — event cancelled",
    body: "The concert I purchased tickets for on April 20 was cancelled. I'd like a full refund for the 2 tickets totalling $180.",
    fromName: "Amara Diallo",
    fromEmail: "amara.diallo@gmail.com",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(12),
  },
  {
    subject: "Refund for software — not as advertised",
    body: "The video editing software I bought doesn't support 4K export as listed on your website. This is false advertising. I want a full refund.",
    fromName: "Nathan Cole",
    fromEmail: "n.cole@icloud.com",
    status: "OPEN",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(3),
  },
  {
    subject: "Course refund within 7-day window",
    body: "I purchased the advanced Python course 3 days ago and it's not what I expected. Per your refund policy I am entitled to a refund. Please process it.",
    fromName: "Lily Tanaka",
    fromEmail: "lily.tanaka@example.com",
    status: "CLOSED",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(30),
  },
  {
    subject: "Double-billed for annual upgrade",
    body: "I upgraded from monthly to annual and was charged both the monthly fee and the annual fee on the same day. Please refund the monthly charge.",
    fromName: "Marcus Webb",
    fromEmail: "m.webb@corporate.io",
    status: "RESOLVED",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(7),
  },

  // TECHNICAL_QUESTION
  {
    subject: "API rate limit errors in production",
    body: "We're hitting 429 rate limit errors on /api/v2/reports even though we're within our stated plan limits. Our plan allows 1000 req/min but we're seeing limits at ~200. Request ID: req_a8f3k.",
    fromName: "Elena Vasquez",
    fromEmail: "elena@devteam.io",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "Webhook not firing on order completion",
    body: "Our webhook endpoint at https://app.example.com/hooks/orders stopped receiving events 2 days ago. Other webhook types (refunds, user signups) are working fine.",
    fromName: "Raj Patel",
    fromEmail: "raj.patel@techstartup.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(2),
  },
  {
    subject: "OAuth2 token refresh failing intermittently",
    body: "Our refresh token flow works ~90% of the time but occasionally returns a 401 even with a valid refresh token that hasn't expired. Happens about 50 times per day across our users.",
    fromName: "Sophie Laurent",
    fromEmail: "sophie.laurent@softwareco.eu",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "CSV export corrupted for large datasets",
    body: "Exporting reports with more than 50,000 rows produces a CSV where the last ~200 rows are garbled. Smaller exports work fine. Browser: Chrome 124.",
    fromName: "Daniel Moreau",
    fromEmail: "d.moreau@analytics.fr",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(9),
  },
  {
    subject: "SSO login broken after Okta update",
    body: "After our Okta org was updated to OIE, SAML logins to your platform stopped working. We get 'Invalid SAML response' error. Our entity ID hasn't changed.",
    fromName: "Chris Huang",
    fromEmail: "chris.huang@enterprise.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "SDK throwing NullPointerException on Android 14",
    body: "After updating to the latest Android SDK (v3.2.1), we're seeing NullPointerException crashes on Android 14 devices when initialising the SDK with a null context. Stack trace attached.",
    fromName: "Yuki Nakamura",
    fromEmail: "yuki.nakamura@mobiledev.jp",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(3),
  },
  {
    subject: "Database migration script failing on Postgres 16",
    body: "Your migration script v4.2 → v4.3 fails on Postgres 16 with 'syntax error at or near USING'. Worked fine on Postgres 14.",
    fromName: "Finn Olsen",
    fromEmail: "finn.olsen@dbadmin.no",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(14),
  },
  {
    subject: "Email notifications going to spam",
    body: "Transactional emails from your platform are landing in spam for our users on Gmail. We've verified our SPF/DKIM but the issue persists. Is your sending domain on any blocklists?",
    fromName: "Aisha Kamara",
    fromEmail: "aisha.kamara@marketingco.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(2),
  },
  {
    subject: "Image uploads failing — 413 error",
    body: "Uploading images larger than 2MB returns a 413 Payload Too Large. Your docs say the limit is 10MB. This started happening yesterday.",
    fromName: "Ben Adeyemi",
    fromEmail: "b.adeyemi@creativeagency.ng",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "Pagination broken — page 2 returns same results as page 1",
    body: "When fetching /api/items?page=2&limit=20, the results are identical to page 1. This happens consistently across different resource types.",
    fromName: "Laura Fernandez",
    fromEmail: "l.fernandez@webapp.es",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(6),
  },
  {
    subject: "Two-factor authentication codes not arriving via SMS",
    body: "Several users report never receiving SMS 2FA codes. Email 2FA works fine. Affected numbers are all on T-Mobile US. Started ~3 days ago.",
    fromName: "Omar Hassan",
    fromEmail: "omar.hassan@operations.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(3),
  },
  {
    subject: "Bulk import API ignoring custom field mappings",
    body: "We're using the bulk import endpoint with a custom field map JSON. The import succeeds but all custom fields are blank — only standard fields are populated.",
    fromName: "Grace Kim",
    fromEmail: "grace.kim@datateam.kr",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(2),
  },
  {
    subject: "Dark mode styles broken after v2.8 update",
    body: "After updating to v2.8 of your desktop app, the dark mode has broken contrast — text and background are both dark grey, making the UI unusable. Rolling back to v2.7 fixes it.",
    fromName: "Leo Ricci",
    fromEmail: "leo.ricci@designer.it",
    status: "CLOSED",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(25),
  },
  {
    subject: "Data sync taking 20+ minutes — used to be instant",
    body: "Full data sync that previously completed in under 30 seconds now takes 20+ minutes. Started around April 25. Our dataset size hasn't changed significantly.",
    fromName: "Maya Robinson",
    fromEmail: "maya.robinson@fintech.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "IP allowlist not blocking non-listed IPs",
    body: "We've configured an IP allowlist for our workspace but users from non-listed IPs can still log in. The allowlist shows as active in settings.",
    fromName: "Thomas Becker",
    fromEmail: "t.becker@securityteam.de",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(2),
  },
  {
    subject: "Zapier integration not triggering on new records",
    body: "Our Zap that triggers on 'new ticket created' stopped firing 4 days ago. The Zapier connection is still authenticated and the test trigger works, but live data doesn't.",
    fromName: "Isabelle Morin",
    fromEmail: "i.morin@automations.ca",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(10),
  },
  {
    subject: "Report charts not rendering in Safari",
    body: "All chart visualisations on the Reports page are blank in Safari 17.4. The data table below the chart loads fine. Chrome and Firefox work correctly.",
    fromName: "Callum Fraser",
    fromEmail: "c.fraser@reporting.co.uk",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(4),
  },
  {
    subject: "Can't connect mobile app — certificate error",
    body: "The iOS app shows 'The certificate for this server is invalid' when connecting to our self-hosted instance. Our cert is valid and the browser works fine. App version 4.1.2.",
    fromName: "Nina Johansson",
    fromEmail: "nina.johansson@selfhosted.se",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "Search indexing lagging by 24+ hours",
    body: "New records are not appearing in full-text search results until the next day. Immediate search was working fine until the platform update on April 29.",
    fromName: "Samuel Eze",
    fromEmail: "samuel.eze@searchtech.ng",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(2),
  },
  {
    subject: "Auto-save deleting content instead of saving",
    body: "The auto-save feature in the document editor is reverting unsaved changes to blank after about 30 seconds. Manually saving (Ctrl+S) works fine.",
    fromName: "Hana Suzuki",
    fromEmail: "hana.suzuki@writingapp.com",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(11),
  },
  {
    subject: "CORS error blocking API calls from our domain",
    body: "We're getting CORS errors when calling /api/v1/data from our front-end at app.ourclient.com. Our domain is listed in the allowed origins in our account settings.",
    fromName: "Aaron Levy",
    fromEmail: "aaron.levy@webdev.com",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "Memory leak in long-running jobs",
    body: "Background jobs that run for more than 2 hours gradually consume all available memory and crash the worker. This started after upgrading to your worker SDK v2.5.",
    fromName: "Fatima Al-Sayed",
    fromEmail: "fatima.alsayed@backend.ae",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(5),
  },
  {
    subject: "Audit log timestamps showing wrong timezone",
    body: "Audit log entries show UTC timestamps but users in GMT+5 see them displayed as if they're in GMT-5. The timezone setting in our account is correct.",
    fromName: "Pedro Gomes",
    fromEmail: "p.gomes@compliance.pt",
    status: "RESOLVED",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(16),
  },

  // GENERAL_QUESTION
  {
    subject: "How do I add a second admin to my account?",
    body: "I'm the only admin right now and want to give my colleague admin access. I can't find where to change her role — she's currently set as 'Member'.",
    fromName: "Rachel Green",
    fromEmail: "r.green@smallbiz.com",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(4),
  },
  {
    subject: "What's the difference between Agent and Admin roles?",
    body: "I'm setting up my team and trying to understand the permission differences between Agent and Admin. Could you outline what each role can and cannot do?",
    fromName: "David Park",
    fromEmail: "david.park@startup.io",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(22),
  },
  {
    subject: "How long is data retained after account cancellation?",
    body: "We're considering cancelling our subscription. I want to know how long you retain our data and what export options are available before it's deleted.",
    fromName: "Stephanie Muller",
    fromEmail: "stephanie.muller@lawfirm.de",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(7),
  },
  {
    subject: "Can I change my billing cycle from monthly to annual?",
    body: "I'd like to switch to annual billing to save on costs. Is it possible to switch mid-cycle, and would I receive a prorated credit for the remaining days?",
    fromName: "Ethan Brooks",
    fromEmail: "ethan.brooks@consultant.com",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(35),
  },
  {
    subject: "Do you offer a non-profit discount?",
    body: "We're a registered 501(c)(3) non-profit and our budget is very limited. Do you have discounted pricing for non-profit organisations?",
    fromName: "Claire Fontaine",
    fromEmail: "claire.fontaine@ngo.org",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "Is there a mobile app available?",
    body: "I'd like to access my account on the go. Is there a native iOS or Android app, or is the only option the mobile browser?",
    fromName: "Kofi Mensah",
    fromEmail: "kofi.mensah@personal.gh",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(45),
  },
  {
    subject: "How do I export all my data?",
    body: "I need to export all tickets, users, and reports to CSV for an internal audit. Is there a bulk export feature or do I need to export each section separately?",
    fromName: "Victoria Russo",
    fromEmail: "v.russo@internal.it",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(10),
  },
  {
    subject: "What payment methods do you accept?",
    body: "I tried to pay with PayPal but it wasn't listed as an option. Do you only accept credit cards? We prefer to pay via invoice/bank transfer for amounts over $500.",
    fromName: "Julius Wagner",
    fromEmail: "julius.wagner@accounting.de",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(28),
  },
  {
    subject: "Can I white-label the customer-facing portal?",
    body: "We want to offer your platform to our own customers under our brand. Is white-labelling available on the Business plan or does it require Enterprise?",
    fromName: "Anastasia Popova",
    fromEmail: "a.popova@agency.ru",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(3),
  },
  {
    subject: "How many seats are included in the Team plan?",
    body: "Your pricing page says 'up to 10 seats' for the Team plan. What counts as a seat — is it per active user per month, or the total number of user accounts?",
    fromName: "Liam O'Brien",
    fromEmail: "liam.obrien@teamco.ie",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(6),
  },
  {
    subject: "Is there a sandbox/test environment available?",
    body: "Before going live, we'd like to test our integration in an isolated sandbox environment. Do you provide one, and is there any additional cost?",
    fromName: "Sana Malik",
    fromEmail: "sana.malik@devteam.pk",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(2),
  },
  {
    subject: "Can two users share a login?",
    body: "We're on the Starter plan with one seat. Can my partner and I share the same login credentials, or does that violate your terms of service?",
    fromName: "Mark Thompson",
    fromEmail: "mark.thompson@freelance.com",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(13),
  },
  {
    subject: "Are you GDPR compliant?",
    body: "We're a European company and need to confirm GDPR compliance before signing up. Do you have a Data Processing Agreement (DPA) we can review and sign?",
    fromName: "Johanna Stein",
    fromEmail: "j.stein@privacy.eu",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(40),
  },
  {
    subject: "How do I delete my account permanently?",
    body: "I'd like to permanently delete my account and all associated data. I couldn't find this option in settings. Please advise on the process.",
    fromName: "Alex Turner",
    fromEmail: "alex.turner@personal.net",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(9),
  },
  {
    subject: "Do you have an uptime SLA?",
    body: "We're evaluating your platform for a critical business process. What is your uptime guarantee, and is there an SLA with compensation clauses for downtime?",
    fromName: "Nadia Osei",
    fromEmail: "n.osei@enterprise.gh",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(2),
  },
  {
    subject: "Can I set up custom email notifications?",
    body: "I want certain team members to get email alerts only for high-priority tickets, not all updates. Is there a way to configure notification rules per user?",
    fromName: "Pierre Renaud",
    fromEmail: "p.renaud@teamlead.fr",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "How do I transfer account ownership?",
    body: "I'm leaving the company and need to transfer the account owner role to my colleague before I go. What's the process? My last day is May 15.",
    fromName: "Sandra Klein",
    fromEmail: "s.klein@leavingco.com",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "Is there a public API for ticket management?",
    body: "We want to build our own dashboard that pulls ticket data. Do you have a public REST or GraphQL API with documentation? And are there any rate limits we should know about?",
    fromName: "Felix Hartmann",
    fromEmail: "felix.hartmann@developer.de",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(8),
  },
  {
    subject: "Do you offer onboarding for Enterprise customers?",
    body: "We're about to sign an Enterprise contract and would like dedicated onboarding support. Is there a customer success manager assigned, and what does the onboarding process look like?",
    fromName: "Jade Thornton",
    fromEmail: "jade.thornton@bigcorp.com",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(50),
  },
  {
    subject: "How do I change the primary email on my account?",
    body: "I recently changed companies and my old email will be deactivated. How do I update the primary email on my account? I still have access to both emails currently.",
    fromName: "Hugo Silva",
    fromEmail: "hugo.silva.old@company.pt",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(5),
  },
  {
    subject: "Can I use my own custom domain for emails?",
    body: "We'd like outbound emails to come from support@ourcompany.com rather than your default domain. Is custom sending domain configuration available?",
    fromName: "Bea Alvarez",
    fromEmail: "bea.alvarez@marketing.es",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(3),
  },
  {
    subject: "What is your data backup policy?",
    body: "How often are backups taken, how long are they retained, and is point-in-time recovery available? We need this information for our business continuity plan.",
    fromName: "Isaac Boateng",
    fromEmail: "i.boateng@risk.gh",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(60),
  },
  {
    subject: "Can I restrict login to company email domains only?",
    body: "We want to prevent anyone with a personal email from accessing our workspace. Is there a domain restriction feature to allow only @ourcompany.com sign-ins?",
    fromName: "Elsa Lindqvist",
    fromEmail: "elsa.lindqvist@security.se",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(15),
  },
  {
    subject: "Do you have an affiliate or referral programme?",
    body: "I recommend your platform to clients regularly. Is there a formal affiliate or referral programme I can join to earn a commission?",
    fromName: "Mike Adkins",
    fromEmail: "mike.adkins@freelancer.com",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(2),
  },
  {
    subject: "Is offline mode supported?",
    body: "Our field teams sometimes work without internet access. Can they work offline and sync data when connectivity is restored? Which features work offline?",
    fromName: "Chiara Esposito",
    fromEmail: "c.esposito@fieldops.it",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(2),
  },
  {
    subject: "How do I generate an invoice for my records?",
    body: "I need a proper VAT invoice for our last three payments for accounting purposes. I can only find receipts in the billing section, not formal invoices with our company details.",
    fromName: "Robert Kaczmarek",
    fromEmail: "r.kaczmarek@finance.pl",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(7),
  },
  {
    subject: "Can I set different access levels per project?",
    body: "We have multiple client projects and want to limit agents to only see tickets for their assigned project. Is project-level access control available?",
    fromName: "Tina Zhao",
    fromEmail: "tina.zhao@agency.cn",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "How do I pause my subscription temporarily?",
    body: "We're going through a quiet period and won't need the platform for 2 months. Is there an option to pause billing rather than cancel and re-subscribe?",
    fromName: "Aaron Svensson",
    fromEmail: "aaron.svensson@seasonal.se",
    status: "OPEN",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "Can I import tickets from Zendesk?",
    body: "We're migrating from Zendesk and have ~3,000 historical tickets. Is there a built-in migration tool or an import format you support to bring them across?",
    fromName: "Valentina Cruz",
    fromEmail: "v.cruz@migration.ar",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(11),
  },

  // No category (null) — uncategorised/new
  {
    subject: "Can't log in — keeps saying invalid password",
    body: "I reset my password twice but still can't log in. The reset email arrives fine and I set a new password, but then it says invalid credentials when I try to sign in.",
    fromName: "Paul Okonkwo",
    fromEmail: "paul.okonkwo@gmail.com",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(0),
  },
  {
    subject: "Invoice not received for April payment",
    body: "My credit card was charged on April 30 but I haven't received an invoice by email. My billing email address is correct in the account settings.",
    fromName: "Hannah Reid",
    fromEmail: "hannah.reid@accounts.co.uk",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(0),
  },
  {
    subject: "Feature request: bulk ticket assignment",
    body: "It would save us a lot of time if we could select multiple tickets and assign them to an agent in one action. Currently we have to do it one by one.",
    fromName: "Diego Morales",
    fromEmail: "diego.morales@support.mx",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(0),
  },
  {
    subject: "App is very slow today",
    body: "The web app has been noticeably slow since this morning — pages take 10+ seconds to load. Is there a known outage or degradation? Our internet is fine.",
    fromName: "Ingrid Holm",
    fromEmail: "ingrid.holm@user.no",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(0),
  },
  {
    subject: "Notification emails not arriving",
    body: "I stopped receiving email notifications for new ticket replies about a week ago. I've checked spam and my email settings — notifications are still enabled in my profile.",
    fromName: "Carlos Reyes",
    fromEmail: "carlos.reyes@business.mx",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(1),
  },
  {
    subject: "Need to update company billing address",
    body: "We've moved offices. I need to update the billing address shown on invoices from our old address to 14 Innovation Drive, Austin TX 78701.",
    fromName: "Janet Wu",
    fromEmail: "janet.wu@company.com",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(1),
  },
  {
    subject: "Getting 500 error when saving settings",
    body: "Every time I click 'Save' on the Notifications Settings page I get a generic 500 error. Other settings pages save fine. Tried in Chrome and Firefox.",
    fromName: "Brandon Scott",
    fromEmail: "b.scott@techuser.com",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(1),
  },
  {
    subject: "Duplicate tickets being created from email",
    body: "When a customer replies to a resolved ticket thread, it's creating a new duplicate ticket instead of reopening the original. This is cluttering our queue.",
    fromName: "Layla Hassan",
    fromEmail: "layla.hassan@supportops.ae",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(2),
  },
  {
    subject: "Text formatting lost when copying from Word",
    body: "When I paste content from a Word document into the ticket editor, all formatting (bold, bullets, headings) is stripped and replaced with plain text.",
    fromName: "Oluwaseun Adebayo",
    fromEmail: "o.adebayo@content.ng",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(2),
  },
  {
    subject: "Filter presets not being saved",
    body: "I create a custom ticket filter and click 'Save as preset' but it disappears after I refresh the page. This has happened three times.",
    fromName: "Margot Leclerc",
    fromEmail: "m.leclerc@user.fr",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(2),
  },
  {
    subject: "Account locked after too many login attempts",
    body: "I accidentally locked myself out after too many wrong password attempts. I've since reset my password but still can't log in. How long does the lockout last?",
    fromName: "Stefan Vogel",
    fromEmail: "stefan.vogel@locked.de",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(0),
  },
  {
    subject: "Ticket status not updating for assigned agent",
    body: "When I change a ticket status from OPEN to RESOLVED, the change shows on my screen but the assigned agent still sees it as OPEN on theirs.",
    fromName: "Amelia Johnson",
    fromEmail: "amelia.j@teamwork.com",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(1),
  },
  {
    subject: "Email thread replies going to wrong ticket",
    body: "Replies to ticket #4421 are being appended to ticket #4412 instead. It seems like the email threading is matching on a partial ID.",
    fromName: "Kwame Asante",
    fromEmail: "kwame.asante@emailops.gh",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(3),
  },
  {
    subject: "Printed ticket summary missing attached files",
    body: "When I use the Print/PDF export function on a ticket, the list of attachments is shown but the files themselves are not embedded. Is this by design?",
    fromName: "Fiona MacLeod",
    fromEmail: "fiona.macleod@paperwork.co.uk",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(3),
  },
  {
    subject: "Agent productivity report showing zero for all agents",
    body: "The Agent Productivity report in Analytics shows 0 tickets resolved for all agents across all date ranges. Tickets are definitely being resolved — the ticket list confirms this.",
    fromName: "Tobias Ritter",
    fromEmail: "t.ritter@analytics.de",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(4),
  },
  {
    subject: "Tags autocomplete not working",
    body: "The tag autocomplete dropdown when adding tags to tickets stopped showing suggestions. I type the first 2 letters but nothing appears. Previously it would suggest existing tags.",
    fromName: "Camille Moreau",
    fromEmail: "c.moreau@tagging.fr",
    status: "RESOLVED",
    category: null,
    createdAt: daysAgo(12),
  },
  {
    subject: "Wrong currency shown on invoices",
    body: "Our account is set to GBP but invoices are being generated in USD. The amounts are not converted — it's the same number but with a dollar sign.",
    fromName: "Oliver Shaw",
    fromEmail: "oliver.shaw@billing.co.uk",
    status: "RESOLVED",
    category: null,
    createdAt: daysAgo(17),
  },
  {
    subject: "Keyboard shortcut for 'Resolve ticket' stopped working",
    body: "The 'R' keyboard shortcut to resolve a ticket no longer works. I'm on the latest version of Chrome on macOS. Other shortcuts like 'A' for assign still work.",
    fromName: "Mei Lin",
    fromEmail: "mei.lin@efficient.cn",
    status: "CLOSED",
    category: null,
    createdAt: daysAgo(33),
  },
  {
    subject: "Subject line truncated in email notifications",
    body: "Email notifications for new tickets truncate the subject at 60 characters. For subjects like 'Cannot process end-of-month payroll export on Windows 11' only the first 60 chars show.",
    fromName: "Nikolai Petrov",
    fromEmail: "n.petrov@email.ru",
    status: "CLOSED",
    category: null,
    createdAt: daysAgo(42),
  },
  {
    subject: "Account showing wrong plan after upgrade",
    body: "I upgraded from Starter to Business 2 days ago. My card was charged the Business plan amount but my account still shows Starter features and limits.",
    fromName: "Alicia Freeman",
    fromEmail: "alicia.freeman@upgrade.com",
    status: "RESOLVED",
    category: null,
    createdAt: daysAgo(8),
  },
  {
    subject: "Customer reply not matching ticket due to forwarding",
    body: "We forward customer emails from our Gmail before they arrive. The 'From' address becomes our Gmail, so every reply creates a new ticket instead of threading. Any workaround?",
    fromName: "Remi Bouchard",
    fromEmail: "remi.bouchard@workflow.fr",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(2),
  },
  {
    subject: "Cannot attach files larger than 5MB",
    body: "Your documentation says attachments up to 25MB are supported, but I get an error when trying to attach files over 5MB. Is there a hidden limit on my plan?",
    fromName: "Darius Ionescu",
    fromEmail: "d.ionescu@attachments.ro",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(1),
  },
  {
    subject: "Ticket counter badge not clearing after reading",
    body: "The red unread ticket counter badge in the sidebar doesn't go away after I've read the tickets. I have to manually mark all as read for it to clear.",
    fromName: "Abena Asare",
    fromEmail: "abena.asare@ui.gh",
    status: "RESOLVED",
    category: null,
    createdAt: daysAgo(19),
  },
  {
    subject: "Email parser stripping HTML tables from ticket body",
    body: "Customers who send emails with HTML tables find their table content is completely removed from the ticket body. Plain text and images come through fine.",
    fromName: "Wolfgang Braun",
    fromEmail: "w.braun@parsing.de",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(4),
  },
  {
    subject: "Sorting by 'Assigned' column not working",
    body: "When I click the 'Assigned' column header to sort tickets by assigned agent, nothing happens. Other columns sort correctly. Using Chrome 124 on Windows 11.",
    fromName: "Luciana Ferreira",
    fromEmail: "luciana.ferreira@ux.br",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(0),
  },
  {
    subject: "Date range filter not inclusive of end date",
    body: "When filtering tickets between May 1–May 7, tickets from May 7 are not included. It seems the end date is exclusive. This is unintuitive and causing missed reports.",
    fromName: "Erik Strand",
    fromEmail: "erik.strand@dates.no",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(1),
  },
  {
    subject: "New ticket form not clearing after submission",
    body: "After submitting a new ticket, the form fields (subject, body, email) remain filled in. If I accidentally submit twice, a duplicate ticket is created.",
    fromName: "Zainab Nkosi",
    fromEmail: "zainab.nkosi@forms.za",
    status: "RESOLVED",
    category: null,
    createdAt: daysAgo(23),
  },
  {
    subject: "Can't see tickets assigned to me on mobile",
    body: "On the mobile web app, the 'Assigned to me' filter shows 0 tickets even though I have 12 open tickets assigned to my account on the desktop version.",
    fromName: "Haruto Yamamoto",
    fromEmail: "haruto.yamamoto@mobile.jp",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(2),
  },
  {
    subject: "Ticket history not showing all changes",
    body: "The activity log on a ticket only shows the last 10 changes. Older events seem to be missing. Is there a limit, and is there a way to see the full history?",
    fromName: "Natasha Ivanova",
    fromEmail: "natasha.ivanova@history.ru",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(3),
  },
  {
    subject: "Custom fields not appearing in ticket export",
    body: "We have 5 custom fields configured on our ticket form. When I export tickets to CSV, these custom fields are not included as columns in the export.",
    fromName: "Bernard Osei",
    fromEmail: "b.osei@export.gh",
    status: "OPEN",
    category: null,
    createdAt: daysAgo(4),
  },
  {
    subject: "Refund for unused annual subscription — company closed",
    body: "Our company shut down and we have 9 months remaining on our annual plan. We would like a prorated refund for the unused portion. Please advise on the process.",
    fromName: "Monica Castillo",
    fromEmail: "monica.castillo@closed.es",
    status: "OPEN",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(2),
  },
  {
    subject: "Cannot delete old team members from account",
    body: "I have 3 former employees listed as agents. When I click the delete icon next to their names, nothing happens. There's no error message either.",
    fromName: "Tony Osei",
    fromEmail: "tony.osei@hr.gh",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(1),
  },
  {
    subject: "How do I set up automatic ticket assignment rules?",
    body: "We want tickets with category 'Technical' to automatically go to our technical team. Is there a routing or assignment rule engine available?",
    fromName: "Catherine Lemaire",
    fromEmail: "c.lemaire@routing.fr",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(6),
  },
  {
    subject: "Response time report showing inflated figures",
    body: "The average first response time on our SLA report shows 48 hours but our team consistently replies within 2 hours. Something seems wrong with how the metric is calculated.",
    fromName: "Emeka Obi",
    fromEmail: "emeka.obi@sla.ng",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(3),
  },
  {
    subject: "Can I schedule a call with your support team?",
    body: "We're a new Enterprise customer and would like to schedule a 30-minute onboarding call to walk through setup. How do I book this?",
    fromName: "Isabella Costa",
    fromEmail: "isabella.costa@enterprise.br",
    status: "CLOSED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(55),
  },
  {
    subject: "Accidental charge on expired card — new card not updated",
    body: "I updated my payment method to a new card last week but was still charged on my expired card today, resulting in a failed payment. Please reprocess on the new card.",
    fromName: "Arjun Mehta",
    fromEmail: "arjun.mehta@billing.in",
    status: "OPEN",
    category: "REFUND_REQUEST",
    createdAt: daysAgo(1),
  },
  {
    subject: "Slack integration not posting ticket updates",
    body: "Our Slack integration was posting ticket status updates to #support-alerts but stopped working 5 days ago. The integration shows as connected in settings.",
    fromName: "Bianca Ferreira",
    fromEmail: "bianca.ferreira@slack.br",
    status: "OPEN",
    category: "TECHNICAL_QUESTION",
    createdAt: daysAgo(5),
  },
  {
    subject: "Need VAT number added to all future invoices",
    body: "Our EU VAT number is EU123456789. Please add it to all future invoices and reissue the last 3 invoices (Feb, Mar, Apr) with the VAT number included for our accounting.",
    fromName: "Heike Schultz",
    fromEmail: "h.schultz@tax.de",
    status: "RESOLVED",
    category: "GENERAL_QUESTION",
    createdAt: daysAgo(9),
  },
];

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(Math.floor(Math.random() * 10) + 8, Math.floor(Math.random() * 60), 0, 0);
  return d;
}

async function main() {
  console.log(`Seeding ${tickets.length} tickets…`);

  // Delete existing seeded tickets to avoid duplication on re-runs
  await prisma.ticket.deleteMany({});
  console.log("Cleared existing tickets.");

  for (const t of tickets) {
    await prisma.ticket.create({
      data: {
        subject: t.subject,
        body: t.body,
        fromName: t.fromName,
        fromEmail: t.fromEmail,
        status: t.status,
        category: t.category ?? undefined,
        createdAt: t.createdAt,
      },
    });
  }

  console.log(`Done — ${tickets.length} tickets created.`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
